/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiSebaranCovid;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Vira
 */
public final class Form_Covid extends javax.swing.JFrame {
    KoneksiDB koneksi = new KoneksiDB();
    int pos;
    

    
    public Form_Covid() {
        initComponents();
        tgl();
        tampil();
    }
    private void tgl (){
        Date ys = new Date();
        SimpleDateFormat s  = new SimpleDateFormat("yyyy-MM-dd");
        tanggal.setText(s.format(ys));
        //tgl.setText(s.format(ys));
    }
    public void kosong (){
        odp.setText("");
        pdp.setText("");
        positif.setText("");
        sembuh.setText("");
        meninggal.setText("");
        kabupaten.setSelectedIndex(-0);
        status.setText("");
}
    public void tampil(){
        DefaultTableModel tabel1= new DefaultTableModel();
        tabel1.addColumn("Tanggal");
        tabel1.addColumn("Kabupaten");
        tabel1.addColumn("ODP");
        tabel1.addColumn("PDP");
        tabel1.addColumn("Positif");
        tabel1.addColumn("Sembuh");
        tabel1.addColumn("Meninggal");
        tabel1.addColumn("Status");
        tabel.setModel(tabel1); 
        String cari = txt_cari.getText();
        try {
            ResultSet res= koneksi.stat.executeQuery("select * from data_covid where nama_kab like '"+cari+"%'");           
            while(res.next()){
                tabel1.addRow(new Object[] {
                    res.getString("tanggal"),
                    res.getString("nama_kab"),
                    res.getString("odp"),
                    res.getString("pdp"),
                    res.getString("positif"),
                    res.getString("sembuh"),
                    res.getString("meninggal"),
                    res.getString("status")
                });
                    tabel.setModel(tabel1);
                }
            } catch (Exception e) {
            
            }    
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tanggal1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        positif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pdp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        odp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        kabupaten = new javax.swing.JComboBox<>();
        tgl = new javax.swing.JLabel();
        sembuh = new javax.swing.JTextField();
        meninggal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        tanggal1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tanggal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggal1MouseClicked(evt);
            }
        });
        tanggal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal1ActionPerformed(evt);
            }
        });
        tanggal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tanggal1KeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("TANGGAL");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Corona.Jogja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 255))); // NOI18N

        positif.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        positif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                positifMouseClicked(evt);
            }
        });
        positif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positifActionPerformed(evt);
            }
        });
        positif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                positifKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("SEMBUH");

        btn_keluar.setBackground(new java.awt.Color(255, 255, 51));
        btn_keluar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 0, 0));
        btn_keluar.setText("LOGOUT");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("KABUPATEN");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("POSITIF");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("SEBARAN COVID-19 DIY");

        btn_hapus.setBackground(new java.awt.Color(255, 255, 51));
        btn_hapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 0, 51));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_ubah.setBackground(new java.awt.Color(255, 255, 51));
        btn_ubah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 0, 51));
        btn_ubah.setText("UBAH");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("MENINGGAL");

        pdp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pdp.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pdpCaretUpdate(evt);
            }
        });
        pdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdpActionPerformed(evt);
            }
        });
        pdp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pdpKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("PDP");

        btn_reset.setBackground(new java.awt.Color(255, 255, 51));
        btn_reset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 0, 51));
        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("ODP");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Cari Berdasarkan Kabupaten :");

        odp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        tabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Kabupaten", "ODP", "PDP", "Positif", "Sembuh", "Meninggal", "Status"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        btn_simpan.setBackground(new java.awt.Color(255, 255, 51));
        btn_simpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 0, 51));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        txt_cari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        kabupaten.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kabupaten.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bantul", "Gunung Kidul", "Kulon Progo", "Sleman", "Yogyakarta" }));

        sembuh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sembuh.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                sembuhCaretUpdate(evt);
            }
        });
        sembuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembuhActionPerformed(evt);
            }
        });
        sembuh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sembuhKeyReleased(evt);
            }
        });

        meninggal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        meninggal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                meninggalCaretUpdate(evt);
            }
        });
        meninggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meninggalActionPerformed(evt);
            }
        });
        meninggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                meninggalKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("STATUS");

        status.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusMouseClicked(evt);
            }
        });
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                statusKeyReleased(evt);
            }
        });

        tanggal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tanggal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tanggalMouseClicked(evt);
            }
        });
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        tanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tanggalKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("TANGGAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 81, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(pdp))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kabupaten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(odp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sembuh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(36, 36, 36)
                                        .addComponent(positif)))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_keluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(267, 267, 267))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(meninggal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btn_keluar)
                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sembuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(positif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(meninggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(62, 62, 62)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_simpan)
                        .addComponent(btn_ubah))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_hapus)
                        .addComponent(btn_reset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String TANGGAL = tanggal.getText();
        String KABUPATEN = (String) kabupaten.getSelectedItem();
        String strODP = odp.getText();
        int ODP = Integer.parseInt(strODP);
        String strPDP = pdp.getText();
        int PDP = Integer.parseInt(strPDP);
        String strPOSITIF = positif.getText();
        int POSITIF = Integer.parseInt(strPOSITIF);
        String strSEMBUH = sembuh.getText();
        int SEMBUH = Integer.parseInt(strSEMBUH);
        String strMENINGGAL = meninggal.getText();
        int MENINGGAL = Integer.parseInt(strMENINGGAL);
        String STATUS = status.getText();

            int konfirm = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Menambah Data ?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);
             if (konfirm == 0){
                JOptionPane.showMessageDialog(null, "Proses Penyimpanan ?");
        {
        String SQL = "insert into data_covid(tanggal,nama_kab,odp,pdp,positif,sembuh,meninggal,status) values ('"+TANGGAL+"','"+KABUPATEN+"', '"+ODP+"',"
                + "'"+PDP+"','"+POSITIF+"','"+SEMBUH+"','"+MENINGGAL+"','"+STATUS+"')";
        //String SQL = "tanggal='"+tanggal.getText()+"',nama_kab='"+kabupaten.getSelectedItem()+"',odp='"+ odp.getText() +"',pdp='"+pdp.getText()+"',positif='"+positif.getText()+"',sembuh='"+sembuh.getText()+"',meninggal='"+meninggal.getText()+"',status='"+status.getText()+"'";
        
        try {
            System.out.println(SQL);
            koneksi.stat.executeUpdate(SQL);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Tambahkan");
            tampil();
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Di Tambahkan");
        }
    }
}
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        String TANGGAL = tanggal.getText();
        String KABUPATEN = (String) kabupaten.getSelectedItem();
        int ODP = Integer.parseInt(odp.getText());
        int PDP = Integer.parseInt(pdp.getText());
        int POSITIF = Integer.parseInt(positif.getText());
        int SEMBUH = Integer.parseInt(sembuh.getText());
        int MENINGGAL = Integer.parseInt(meninggal.getText());
        String STATUS = status.getText();
            int konfirm = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Mengubah Data ?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
                if (konfirm == 0){
                JOptionPane.showMessageDialog(null, "Proses Penyimpanan ?");
        {
        String SQL = "update data_covid set tanggal='"+TANGGAL+"',nama_kab='"+KABUPATEN+"',odp='"+ODP+"',pdp='"+PDP+"',"
                + "positif='"+POSITIF+"',sembuh='"+SEMBUH+"',meninggal='"+MENINGGAL+"',status='"+STATUS+"' where nama_kab='"+KABUPATEN+"'";
        System.out.println(SQL);
        try {
            koneksi.stat.executeUpdate(SQL);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Ubah");
            tampil();
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Di Ubah");
        }
    }
}
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        String KABUPATEN      = (String) kabupaten.getSelectedItem();
            int konfirm = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Menghapus Data ?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION);
             if (konfirm == 0){
                JOptionPane.showMessageDialog(null, "Proses Menghapus ?");
        {
        String SQL = "delete from data_covid where nama_kab=('"+ KABUPATEN +"')";
        System.out.println(SQL);
        try {
            koneksi.stat.executeUpdate(SQL);
            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Di Hapus");
            tampil();
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Di Hapus");
        }
    }
}
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
       kosong();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        Form_Login login = new Form_Login();
        login.setVisible(true);
        dispose();
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void positifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positifActionPerformed

    private void positifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_positifMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_positifMouseClicked

    private void positifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_positifKeyReleased
        /* TODO add your handling code here:
        berat = Integer.parseInt(semester.getText());
        harga = 5000;
        total_bayar = berat*5000;
        txt_ttlbyr.setText(String.valueOf(total_bayar));
        txt_harga.setText(String.valueOf(harga));*/
    }//GEN-LAST:event_positifKeyReleased

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_txt_cariKeyReleased

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        tanggal.setText(tabel.getValueAt(tabel.getSelectedRow(), 0).toString());
        kabupaten.setSelectedItem(tabel.getValueAt(tabel.getSelectedRow(), 1).toString());
        odp.setText(tabel.getValueAt(tabel.getSelectedRow(), 2).toString());
        pdp.setText(tabel.getValueAt(tabel.getSelectedRow(), 3).toString());
        positif.setText(tabel.getValueAt(tabel.getSelectedRow(), 4).toString());
        sembuh.setText(tabel.getValueAt(tabel.getSelectedRow(), 5).toString());
        meninggal.setText(tabel.getValueAt(tabel.getSelectedRow(), 6).toString());
        status.setText(tabel.getValueAt(tabel.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_tabelMouseClicked

    private void pdpCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pdpCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_pdpCaretUpdate

    private void pdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pdpActionPerformed

    private void pdpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pdpKeyReleased
        /* TODO add your handling code here:
        String No_antri = nama.getText();
         try{
            com.mysql.jdbc.Statement statement=(com.mysql.jdbc.Statement)koneksi.stat.getConnection().createStatement();
            ResultSet res=statement.executeQuery("select * from tabel_pemesanan where No_antrian='"+No_antri+"'");
            while(res.next()){
                nama.setText(res.getString("No_antrian"));
                txt_namapel.setText(res.getString(3));
                alamat.setText(res.getString(4));
                txt_notlp.setText(res.getString(5));
                semester.setText(res.getString(6));
                txt_harga.setText(res.getString(7));
                txt_ttlbyr.setText(res.getString(8));            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Salah");
        }*/
    }//GEN-LAST:event_pdpKeyReleased

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void sembuhCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_sembuhCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_sembuhCaretUpdate

    private void sembuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembuhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sembuhActionPerformed

    private void sembuhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sembuhKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sembuhKeyReleased

    private void meninggalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_meninggalCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_meninggalCaretUpdate

    private void meninggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meninggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meninggalActionPerformed

    private void meninggalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meninggalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_meninggalKeyReleased

    private void statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_statusMouseClicked

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void statusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusKeyReleased
       pos = Integer.parseInt(positif.getText());
       if(pos > 0) {
       status.setText("Zona Merah");
       } else {
       status.setText("Zona Hijau");
       }
    }//GEN-LAST:event_statusKeyReleased

    private void tanggalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalMouseClicked

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void tanggalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tanggalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalKeyReleased

    private void tanggal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tanggal1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal1MouseClicked

    private void tanggal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal1ActionPerformed

    private void tanggal1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tanggal1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Form_Covid().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JComboBox<String> kabupaten;
    private javax.swing.JTextField meninggal;
    private javax.swing.JTextField odp;
    private javax.swing.JTextField pdp;
    private javax.swing.JTextField positif;
    private javax.swing.JTextField sembuh;
    private javax.swing.JTextField status;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tanggal1;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
